### ISSUE TITLE
Mysql2::Error: Specified key was too long

### ISSUE THREAD

**Issue by kmcphillips** [fractaledmind/solid_errors#1]
## Problem

When using MySQL 8 the generated index for the supplied migration is too long:

```
 bin/rails db:migrate            
== 20240128190608 CreateSolidErrorsTables: migrating ==========================
-- create_table(:solid_errors)
bin/rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

Mysql2::Error: Specified key was too long; max key length is 3072 bytes
/app/db/migrate/20240128190608_create_solid_errors_tables.rb:5:in `change'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 3072 bytes (ActiveRecord::StatementInvalid)
/app/db/migrate/20240128190608_create_solid_errors_tables.rb:5:in `change'

Caused by:
Mysql2::Error: Specified key was too long; max key length is 3072 bytes (Mysql2::Error)
/app/db/migrate/20240128190608_create_solid_errors_tables.rb:5:in `change'
```

## Replication

On a Rails 7.1 app, using MySQL 8 and the `mysql2` gem, on Ruby 3.2.2, run the generator and migrate.

```
mysql --version                                                                                      
mysql  Ver 8.0.35-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))
cat /etc/issue  
Ubuntu 22.04.3 LTS
```

**Comment by kmcphillips** [comment]
I'm doing some reading and this may be affected by the DB collation and utf8.

**Comment by fractaledmind** [comment]
What version of the gem did you run the installer with? 0.3.0 didn't explicitly set the index name, and it could be too long. Version 0.3.3 is the current version with some initial fixes for the gem after initial public release.

**Comment by kmcphillips** [comment]
Oh here I thought I was putting in all the important detail and somehow I didn't include the gem version.

I was on `0.3.0`. I did a clean retry with `0.3.3` and have the same error. 

The reading I was doing about this was that it's the _key_ is too long, not the name of the key. So four `VARCHAR(255)`s with unicode encoding size overflows the max length of the key data.

The reason I opened an issue and not a PR is I don't know exactly how this index is used, but for MySQL it means either:
* Using multiple indexes that are smaller, rather than this one big cascading one.
* Using smaller fields for some of the fields to try to fit them into the max length of the key.

**Comment by fractaledmind** [comment]
The `severity` and `exception_class` fields can be limited. Can you try adding `limit: 25` to the severity field and `limit: 200` to the exception_class field? I _think_ that should be sufficient, but only you can confirm as I can't repro this particular problem.

My guess is that the current key byte size is 4,080 (`(255*4)*4 == 4080`). These two limitations should be sufficient, as `((255*4)*2)+(25*4)+(200*4) == 2940`.

I need to index on all 4 columns, as this is what defines a unique error, which is important for driving the resolution and occurrence logic.

**Comment by kmcphillips** [comment]
I agree with that math! I limited to 200 and 25 and:

```
bin/rails db:migrate
== 20240129000015 CreateSolidErrorsTables: migrating ==========================
-- create_table(:solid_errors)
   -> 0.0220s
-- create_table(:solid_errors_occurrences)
   -> 0.0082s
== 20240129000015 CreateSolidErrorsTables: migrated (0.0303s) =================
