### ISSUE TITLE
"ActionView::Template::Error (Broken pipe)" is not recorded

### ISSUE THREAD

**Issue by dorianmariecom** [fractaledmind/solid_errors#18]
(it's because I didn't install pandoc)

See backtrace:

```
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] ActionView::Template::Error (Broken pipe):
[b685f3fd-3d23-4a0e-921d-eb54289dca4e]   
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] pandoc-ruby (2.1.10) lib/pandoc-ruby.rb:291:in `write'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] pandoc-ruby (2.1.10) lib/pandoc-ruby.rb:291:in `puts'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] pandoc-ruby (2.1.10) lib/pandoc-ruby.rb:291:in `block (2 levels) in execute'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] /opt/rubies/ruby-3.3.0/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] /opt/rubies/ruby-3.3.0/lib/ruby/3.3.0/timeout.rb:41:in `handle_timeout'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] /opt/rubies/ruby-3.3.0/lib/ruby/3.3.0/timeout.rb:195:in `timeout'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] pandoc-ruby (2.1.10) lib/pandoc-ruby.rb:290:in `block in execute'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] /opt/rubies/ruby-3.3.0/lib/ruby/3.3.0/open3.rb:540:in `popen_run'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] /opt/rubies/ruby-3.3.0/lib/ruby/3.3.0/open3.rb:235:in `popen3'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] pandoc-ruby (2.1.10) lib/pandoc-ruby.rb:288:in `execute'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] pandoc-ruby (2.1.10) lib/pandoc-ruby.rb:278:in `execute_pandoc'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] pandoc-ruby (2.1.10) lib/pandoc-ruby.rb:270:in `convert_string'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] pandoc-ruby (2.1.10) lib/pandoc-ruby.rb:206:in `convert'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] pandoc-ruby (2.1.10) lib/pandoc-ruby.rb:242:in `block (2 levels) in <class:PandocRuby>'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] tilt (2.3.0) lib/tilt/pandoc.rb:38:in `block in <main>'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] tilt (2.3.0) lib/tilt/template.rb:446:in `prepare'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] tilt (2.3.0) lib/tilt/template.rb:95:in `initialize'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] slim (5.2.1) lib/slim/embedded.rb:171:in `new'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] slim (5.2.1) lib/slim/embedded.rb:171:in `tilt_render'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] slim (5.2.1) lib/slim/embedded.rb:139:in `on_slim_embedded'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] slim (5.2.1) lib/slim/embedded.rb:104:in `on_slim_embedded'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:71:in `dispatcher'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:50:in `compile'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:8:in `block in on_multi'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:8:in `each'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:8:in `on_multi'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:111:in `dispatcher'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:50:in `compile'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/html/dispatcher.rb:28:in `on_html_tag'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:84:in `dispatcher'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:50:in `compile'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:8:in `block in on_multi'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:8:in `each'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:8:in `on_multi'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:111:in `dispatcher'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:50:in `compile'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/dispatcher.rb:46:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/engine.rb:51:in `block in call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/engine.rb:51:in `each'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/engine.rb:51:in `inject'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/engine.rb:51:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/mixins/template.rb:11:in `compile'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] temple (0.10.3) lib/temple/templates/rails.rb:13:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/template.rb:422:in `compiled_source'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/template.rb:474:in `compile'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/template.rb:409:in `block (2 levels) in compile!'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/notifications.rb:208:in `instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/template.rb:545:in `instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/template.rb:408:in `block in compile!'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/template.rb:400:in `synchronize'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/template.rb:400:in `compile!'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/template.rb:250:in `block in render'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/notifications.rb:208:in `instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/template.rb:549:in `instrument_render_template'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/template.rb:249:in `render'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/renderer/template_renderer.rb:66:in `block (2 levels) in render_template'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/notifications.rb:206:in `block in instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/notifications.rb:206:in `instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/renderer/template_renderer.rb:76:in `block in render_with_layout'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/notifications.rb:206:in `block in instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/notifications.rb:206:in `instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/renderer/template_renderer.rb:75:in `render_with_layout'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/renderer/template_renderer.rb:11:in `render'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/renderer/renderer.rb:63:in `render_template_to_object'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/renderer/renderer.rb:31:in `render_to_object'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/rendering.rb:135:in `block in _render_template'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/base.rb:291:in `in_rendering_context'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/rendering.rb:134:in `_render_template'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/streaming.rb:256:in `_render_template'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/rendering.rb:121:in `render_to_body'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/rendering.rb:158:in `render_to_body'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/abstract_controller/rendering.rb:27:in `render'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/rendering.rb:139:in `render'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/instrumentation.rb:29:in `block (2 levels) in render'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] /opt/rubies/ruby-3.3.0/lib/ruby/3.3.0/benchmark.rb:313:in `realtime'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/core_ext/benchmark.rb:14:in `ms'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/instrumentation.rb:29:in `block in render'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/instrumentation.rb:98:in `cleanup_view_runtime'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activerecord (7.1.3) lib/active_record/railties/controller_runtime.rb:39:in `cleanup_view_runtime'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/instrumentation.rb:28:in `render'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/implicit_render.rb:37:in `default_render'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/basic_implicit_render.rb:7:in `send_action'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/abstract_controller/base.rb:224:in `process_action'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/rendering.rb:165:in `process_action'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/abstract_controller/callbacks.rb:259:in `block in process_action'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/callbacks.rb:121:in `block in run_callbacks'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] turbo-rails (2.0.2) lib/turbo-rails.rb:24:in `with_request_id'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] turbo-rails (2.0.2) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actiontext (7.1.3) lib/action_text/rendering.rb:23:in `with_renderer'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actiontext (7.1.3) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/callbacks.rb:130:in `instance_exec'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/callbacks.rb:130:in `block in run_callbacks'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/callbacks.rb:141:in `run_callbacks'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/abstract_controller/callbacks.rb:258:in `process_action'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/rescue.rb:25:in `process_action'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/notifications.rb:206:in `block in instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/notifications/instrumenter.rb:58:in `instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/notifications.rb:206:in `instrument'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/instrumentation.rb:73:in `process_action'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal/params_wrapper.rb:261:in `process_action'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activerecord (7.1.3) lib/active_record/railties/controller_runtime.rb:32:in `process_action'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/abstract_controller/base.rb:160:in `process'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionview (7.1.3) lib/action_view/rendering.rb:40:in `process'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal.rb:227:in `dispatch'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_controller/metal.rb:309:in `dispatch'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/journey/router.rb:51:in `block in serve'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/journey/router.rb:124:in `each'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/journey/router.rb:124:in `find_routes'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/journey/router.rb:32:in `serve'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/routing/route_set.rb:882:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] rack (3.0.9) lib/rack/tempfile_reaper.rb:20:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] rack (3.0.9) lib/rack/etag.rb:29:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] rack (3.0.9) lib/rack/conditional_get.rb:31:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] rack (3.0.9) lib/rack/head.rb:15:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/http/permissions_policy.rb:36:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/http/content_security_policy.rb:33:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/middleware/cookies.rb:689:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/callbacks.rb:101:in `run_callbacks'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] railties (7.1.3) lib/rails/rack/logger.rb:37:in `call_app'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] railties (7.1.3) lib/rails/rack/logger.rb:24:in `block in call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/tagged_logging.rb:135:in `block in tagged'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/tagged_logging.rb:39:in `tagged'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/tagged_logging.rb:135:in `tagged'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] activesupport (7.1.3) lib/active_support/broadcast_logger.rb:240:in `method_missing'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] railties (7.1.3) lib/rails/rack/logger.rb:24:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/middleware/request_id.rb:28:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] rack (3.0.9) lib/rack/method_override.rb:28:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] rack (3.0.9) lib/rack/runtime.rb:24:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/middleware/static.rb:25:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] rack (3.0.9) lib/rack/sendfile.rb:114:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/middleware/ssl.rb:79:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] actionpack (7.1.3) lib/action_dispatch/middleware/assume_ssl.rb:21:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] railties (7.1.3) lib/rails/engine.rb:536:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] puma (6.4.2) lib/puma/configuration.rb:272:in `call'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] puma (6.4.2) lib/puma/server.rb:464:in `process_client'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] puma (6.4.2) lib/puma/server.rb:245:in `block in run'
[b685f3fd-3d23-4a0e-921d-eb54289dca4e] puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by fractaledmind** [comment]
Can you try an experiment with the same app and same error, but on the `HEAD` of the `rails` repo? 

That callstack looks like what the stacks look like when Rails doesn't record errors in production. Specifically, when you only see the `lib/action_dispatch/middleware/executor.rb` called _once_ on the current version of Rails, you won't get the error recorded. But, I would hope that the fix in `rails` now would resolve this problem as well.

If you can test that hypothesis and prove it true, that would be awesome!

**Comment by dorianmariecom** [comment]
It's fixed in rails main, thanks <3

![Screenshot 2024-02-14 at 19 49 14](https://github.com/fractaledmind/solid_errors/assets/58794487/93880c40-e675-4912-8649-841705278dae)
